import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms and conditions for using AI Portfolio Reviewer.',
}

export default function TermsPage() {
  return (
    <div className="container max-w-2xl py-16">
      <Link
        href="/"
        className="mb-8 flex items-center gap-1.5 text-sm text-muted-foreground transition-colors hover:text-foreground"
      >
        <ArrowLeft className="h-4 w-4" />
        Back
      </Link>

      <div className="mb-10 flex flex-col gap-2">
        <h1 className="text-2xl font-bold tracking-tight text-foreground">Terms of Service</h1>
        <p className="text-sm text-muted-foreground">Last updated: May 2026</p>
      </div>

      <div className="prose prose-sm dark:prose-invert max-w-none">
        <h2>1. Acceptance</h2>
        <p>
          By using AI Portfolio Reviewer you agree to these terms. If you do not agree, do not use
          the service.
        </p>

        <h2>2. Use of the service</h2>
        <p>
          You may use this service to analyze your own CV and professional documents. You may not
          submit third-party documents without their consent, or use the service for any unlawful
          purpose.
        </p>

        <h2>3. AI-generated content</h2>
        <p>
          Analysis results are generated by AI and are for informational purposes only. They do not
          constitute professional career advice. We make no guarantees about accuracy or outcomes.
        </p>

        <h2>4. Account responsibility</h2>
        <p>
          You are responsible for maintaining the confidentiality of your account credentials and
          for all activity that occurs under your account.
        </p>

        <h2>5. Limitation of liability</h2>
        <p>
          The service is provided \'as is\' without warranties of any kind. We are not liable for
          any indirect, incidental, or consequential damages arising from use of the service.
        </p>

        <h2>6. Changes to terms</h2>
        <p>
          We reserve the right to update these terms at any time. Continued use of the service
          after changes constitutes acceptance.
        </p>
      </div>
    </div>
  )
}
